BEGIN;

ALTER TABLE public.reward_point_ledger
  DROP CONSTRAINT IF EXISTS reward_point_ledger_source_type_check;

ALTER TABLE public.reward_point_ledger
  ADD CONSTRAINT reward_point_ledger_source_type_check
  CHECK (
    source_type IN (
      'service_delivery',
      'google_review',
      'facebook_review',
      'campaign_bonus',
      'reward_redeem',
      'reward_use',
      'reward_cancel',
      'reward_refund',
      'manual_adjust',
      'system_adjust'
    )
  );

CREATE TABLE IF NOT EXISTS public.reward_campaign_claims (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_code text NOT NULL,
  customer_id integer NOT NULL REFERENCES public.customers(id) ON UPDATE CASCADE ON DELETE CASCADE,
  account_id integer NOT NULL REFERENCES public.reward_accounts(id) ON UPDATE CASCADE ON DELETE CASCADE,
  ledger_id integer UNIQUE REFERENCES public.reward_point_ledger(id) ON UPDATE CASCADE ON DELETE SET NULL,
  branch_id integer NOT NULL REFERENCES public.branches(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  points_awarded integer NOT NULL DEFAULT 1 CHECK (points_awarded > 0),
  line_user_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  claimed_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (campaign_code, customer_id)
);

CREATE INDEX IF NOT EXISTS idx_reward_campaign_claims_customer_id
  ON public.reward_campaign_claims(customer_id);

CREATE OR REPLACE FUNCTION public.claim_welcome_bonus_1_point(p_line_user_id text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_campaign_code constant text := 'WELCOME_1_POINT_2026';
  v_points constant integer := 1;
  v_customer record;
  v_account record;
  v_claim record;
  v_ledger record;
  v_balance_before integer;
  v_balance_after integer;
BEGIN
  IF p_line_user_id IS NULL OR length(trim(p_line_user_id)) = 0 THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'กรุณา login LINE ใหม่'
    );
  END IF;

  SELECT id, branch_id, name, customer_code
    INTO v_customer
  FROM public.customers
  WHERE line_user_id = p_line_user_id
  LIMIT 1;

  IF v_customer.id IS NULL THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'ไม่พบลูกค้า กรุณาผูกบัญชีก่อนรับแต้ม'
    );
  END IF;

  INSERT INTO public.reward_accounts (customer_id, branch_id)
  VALUES (v_customer.id, v_customer.branch_id)
  ON CONFLICT (customer_id) DO NOTHING;

  SELECT *
    INTO v_account
  FROM public.reward_accounts
  WHERE customer_id = v_customer.id
  FOR UPDATE;

  SELECT *
    INTO v_claim
  FROM public.reward_campaign_claims
  WHERE campaign_code = v_campaign_code
    AND customer_id = v_customer.id;

  IF v_claim.id IS NOT NULL THEN
    RETURN jsonb_build_object(
      'success', true,
      'claimed', true,
      'already_claimed', true,
      'points_awarded', 0,
      'balance_before', v_account.current_points,
      'balance_after', v_account.current_points,
      'campaign_code', v_campaign_code,
      'ledger_id', v_claim.ledger_id
    );
  END IF;

  v_balance_before := v_account.current_points;
  v_balance_after := v_balance_before + v_points;

  INSERT INTO public.reward_point_ledger (
    account_id,
    customer_id,
    branch_id,
    source_type,
    points_delta,
    balance_after,
    idempotency_key,
    actor_type,
    actor_customer_id,
    note,
    metadata
  )
  VALUES (
    v_account.id,
    v_customer.id,
    v_customer.branch_id,
    'campaign_bonus',
    v_points,
    v_balance_after,
    'campaign:' || v_campaign_code || ':customer:' || v_customer.id,
    'customer',
    v_customer.id,
    'รับแต้มฟรี 1 แต้ม',
    jsonb_build_object(
      'transaction_type', 'earn',
      'source_type', 'campaign_bonus',
      'source_id', v_campaign_code,
      'campaign_code', v_campaign_code,
      'campaign_name', 'รับแต้มฟรี 1 แต้ม',
      'line_user_id', p_line_user_id
    )
  )
  RETURNING *
  INTO v_ledger;

  UPDATE public.reward_accounts
  SET current_points = v_balance_after,
      lifetime_earned_points = lifetime_earned_points + v_points,
      updated_at = now()
  WHERE id = v_account.id;

  INSERT INTO public.reward_campaign_claims (
    campaign_code,
    customer_id,
    account_id,
    ledger_id,
    branch_id,
    points_awarded,
    line_user_id,
    metadata
  )
  VALUES (
    v_campaign_code,
    v_customer.id,
    v_account.id,
    v_ledger.id,
    v_customer.branch_id,
    v_points,
    p_line_user_id,
    jsonb_build_object('campaign_name', 'รับแต้มฟรี 1 แต้ม')
  )
  RETURNING *
  INTO v_claim;

  RETURN jsonb_build_object(
    'success', true,
    'claimed', true,
    'already_claimed', false,
    'points_awarded', v_points,
    'balance_before', v_balance_before,
    'balance_after', v_balance_after,
    'campaign_code', v_campaign_code,
    'ledger_id', v_ledger.id,
    'claim_id', v_claim.id
  );
EXCEPTION
  WHEN unique_violation THEN
    SELECT *
      INTO v_account
    FROM public.reward_accounts
    WHERE customer_id = v_customer.id;

    SELECT *
      INTO v_claim
    FROM public.reward_campaign_claims
    WHERE campaign_code = v_campaign_code
      AND customer_id = v_customer.id;

    RETURN jsonb_build_object(
      'success', true,
      'claimed', true,
      'already_claimed', true,
      'points_awarded', 0,
      'balance_before', COALESCE(v_account.current_points, 0),
      'balance_after', COALESCE(v_account.current_points, 0),
      'campaign_code', v_campaign_code,
      'ledger_id', v_claim.ledger_id
    );
END;
$$;

COMMIT;
